### ISSUE TITLE
Add product lifecycle to `sdk/`

### ISSUE THREAD

**Issue by QuintinWillison** [ably/engineering#5]
I've briefly discussed this with @AndyNicks and we both feel that this information should be in the public domain.

**Document Scope:** Labs, Alpha, Technical Preview, Beta, Release Candidate, General Availability, Limited Support, End of Life - plus the [SemVer](https://semver.org/) pre-release suffixes we use for stages, where applicable.

**Source Document:** [SDK Product Lifecycle](https://ably.atlassian.net/wiki/spaces/product/pages/1628405776/SDK+Product+Lifecycle) (internal Confluence)

**Steps:**

1. Convert origin document to markdown and add to this repository
2. Once landed to `main` branch, replace contents of origin document with note to state that it's moved here

**Comment by kavalerov** [comment]
I was actually thinking that we should add this to the general docs, because the document can cover more than just SDK lifecycle - also product feature lifecycle and such.

**Comment by QuintinWillison** [comment]
Fixed by https://github.com/ably/engineering/commit/b6d9c30503388f7e27362a7cba23eafeac086ee5.
